use QUANLYBANHANG;

-------------------------Bai tap phan III------------------------------

-- 12.
SELECT DISTINCT SOHD 
FROM CTHD
WHERE SL >= 10
AND SL <= 20
AND MASP IN ('BB01','BB02');

-- 13. 
SELECT DISTINCT SOHD
FROM CTHD 
WHERE MASP = 'BB01'
AND SL BETWEEN 10 AND 20
INTERSECT
SELECT DISTINCT SOHD
FROM CTHD 
WHERE MASP = 'BB02'
AND SL BETWEEN 10 AND 20;
