use QUANLYGIAOVU;

-------------------------Bai tap phan II------------------------------

--1
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE GIAOVIEN.MAGV = (SELECT KHOA.TRGKHOA FROM  KHOA
WHERE GIAOVIEN.MAGV = KHOA.TRGKHOA);

--2
UPDATE HOCVIEN
SET DIEMTB = (
    SELECT AVG(DIEM)
    FROM (
        SELECT MAHV, MAMH, MAX(LANTHI) AS LANTHI
        FROM KETQUATHI
        GROUP BY MAHV, MAMH
    ) AS KQ
    INNER JOIN KETQUATHI ON KQ.MAHV = KETQUATHI.MAHV AND KQ.MAMH = KETQUATHI.MAMH AND KQ.LANTHI = KETQUATHI.LANTHI
);

--3
UPDATE KETQUATHI
SET GHICHU = 'Cam thi'
WHERE LANTHI = 3 AND DIEM < 5;

--4
UPDATE HOCVIEN
SET XEPLOAI = CASE
    WHEN DIEMTB >= 9 THEN 'XS'
    WHEN DIEMTB >= 8 THEN 'G'
    WHEN DIEMTB >= 6.5 THEN 'K'
    WHEN DIEMTB >= 5 THEN 'TB'
    ELSE 'Y'
END;
