use QUANLYBANHANG;

-------------------------Bai tap phan III------------------------------

-- 14. 
SELECT DISTINCT SANPHAM.MASP,SANPHAM.TENSP
FROM HOADON JOIN CTHD 
ON CTHD.SOHD = HOADON.SOHD 
JOIN SANPHAM  
ON SANPHAM.MASP = CTHD.MASP
WHERE NUOCSX = 'Trung Quoc' 
OR NGHD = '01/01/2007';

-- 15. 
SELECT MASP, TENSP
FROM SANPHAM
WHERE NOT EXISTS (SELECT * FROM CTHD
WHERE SANPHAM.MASP = CTHD.MASP);

-- 16. 
SELECT SANPHAM.MASP,TENSP
FROM SANPHAM
EXCEPT
SELECT SANPHAM.MASP,TENSP
FROM CTHD JOIN SANPHAM 
ON SANPHAM.MASP = CTHD.MASP
JOIN HOADON 
ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = 2006;

-- 17. 
SELECT SANPHAM.MASP,TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
EXCEPT
SELECT SANPHAM.MASP,TENSP
FROM CTHD JOIN SANPHAM 
ON SANPHAM.MASP = CTHD.MASP
JOIN HOADON 
ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = 2006;

-- 18. 
SELECT SOHD
FROM HOADON
WHERE NOT EXISTS (SELECT * FROM SANPHAM 
WHERE NUOCSX = 'Singapore' 
AND NOT EXISTS (SELECT * FROM CTHD 
WHERE HOADON.SOHD=CTHD.SOHD 
AND CTHD.MASP=SANPHAM.MASP));

-- 19. 
SELECT SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2006 
AND NOT EXISTS (SELECT * FROM SANPHAM 
WHERE NUOCSX = 'Singapore' 
AND NOT EXISTS (SELECT * FROM CTHD 
WHERE HOADON.SOHD=CTHD.SOHD 
AND CTHD.MASP=SANPHAM.MASP));

