use QUANLYGIAOVU;

-------------------------Bai tap phan III------------------------------

--11
SELECT DISTINCT HOTEN
FROM GIAOVIEN JOIN GIANGDAY 
ON GIAOVIEN.MAGV = GIANGDAY.MAGV
WHERE GIANGDAY.NAM = 2006
AND GIANGDAY.HOCKY = 1
AND MAMH = 'CTRR'
AND GIANGDAY.MALOP IN ('K11', 'K12');

--12
SELECT HOCVIEN.MAHV, HO, TEN
FROM HOCVIEN
WHERE MAHV IN (SELECT MAHV FROM KETQUATHI
WHERE MAMH = 'CSDL'
AND KQUA = 'Khong Dat'
EXCEPT 
SELECT DISTINCT MAHV
FROM KETQUATHI
WHERE MAMH = 'CSDL'
AND LANTHI > 1);

--13
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV NOT IN (
SELECT DISTINCT MAGV
FROM GIANGDAY);

--14
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV NOT IN (
    SELECT DISTINCT MAGV
    FROM GIANGDAY
    WHERE MAMH IN (
        SELECT MAMH
        FROM MONHOC
        WHERE MAKHOA = (
            SELECT MAKHOA
            FROM GIAOVIEN
            WHERE MAGV = GIANGDAY.MAGV
        )
    )
);

--15
SELECT HO, TEN
FROM HOCVIEN
WHERE MAHV IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE MALOP = 'K11' AND LANTHI > 3 AND KQUA = 'Khong dat'
) OR MAHV IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE MALOP = 'K11' AND MAMH = (
        SELECT MAMH
        FROM MONHOC
        WHERE TENMH = 'CTRR'
    ) AND LANTHI = 2 AND DIEM = 5
);

--16
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
    SELECT MAGV
    FROM GIANGDAY
    WHERE MAMH = (
        SELECT MAMH
        FROM MONHOC
        WHERE TENMH = 'CTRR'
    )
    GROUP BY MAGV, HOCKY, NAM
    HAVING COUNT(DISTINCT MALOP) >= 2);

--17
SELECT MAHV, DIEM
FROM KETQUATHI
WHERE MAMH = (
SELECT MAMH
FROM MONHOC
WHERE TENMH = 'CSDL'
) AND (MAHV, MAMH, LANTHI) IN (
SELECT MAHV, MAMH, MAX(LANTHI)
FROM KETQUATHI
GROUP BY MAHV, MAMH);

--18
SELECT MAHV, MAX(DIEM)
FROM KETQUATHI
WHERE MAMH = (
SELECT MAMH
FROM MONHOC
WHERE TENMH = 'Co So Du Lieu'
)
GROUP BY MAHV;
