use QUANLYBANHANG;

-------------------------Bai tap phan III------------------------------

-- 20. 
SELECT COUNT(SOHD) AS 'KET QUA'
FROM CTHD
WHERE SOHD IN (SELECT SOHD
				FROM HOADON
				EXCEPT
				SELECT SOHD 
				FROM HOADON
				WHERE MAKH  IN (SELECT MAKH 
								FROM KHACHHANG))

-- 21. 
SELECT COUNT(DISTINCT MASP) AS 'SO SP KHAC NHAU'
FROM SANPHAM
WHERE MASP IN (SELECT DISTINCT MASP 
				FROM CTHD
				WHERE SOHD IN (SELECT DISTINCT SOHD
								FROM HOADON
								WHERE YEAR(NGHD) = 2006))

-- 22. 
SELECT MAX(TRIGIA) AS 'MAX', MIN(TRIGIA) AS 'MIN'
FROM HOADON

-- 23. 
SELECT AVG(TRIGIA) AS 'GIA TRI TRUNG BINH HOA DON 2006'
FROM HOADON 

-- 24. 
SELECT SUM(TRIGIA) AS 'DOANH THU 2006'
FROM HOADON

-- 25. 
SELECT SOHD 
FROM HOADON
WHERE YEAR(NGHD) = 2006
	AND TRIGIA = (SELECT MAX(TRIGIA)
					FROM HOADON
					WHERE YEAR(NGHD) = 2006)

-- 26.
SELECT HOTEN 
FROM KHACHHANG 
WHERE MAKH IN (SELECT MAKH
				FROM HOADON
				WHERE YEAR(NGHD) = 2006
					AND TRIGIA = (SELECT MAX(TRIGIA)
									FROM HOADON
									WHERE YEAR(NGHD) = 2006))

-- 27. 
SELECT TOP 3 MAKH, HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC

-- 28. 
SELECT MASP, TENSP
FROM SANPHAM
WHERE GIA IN (SELECT DISTINCT TOP 3 GIA
			  FROM SANPHAM
			  ORDER BY GIA DESC)

-- 29. 
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan'
	AND GIA IN (SELECT DISTINCT TOP 3 GIA
				FROM SANPHAM
				ORDER BY GIA DESC)

-- 30.
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
	AND GIA IN (SELECT DISTINCT TOP 3 GIA
				  FROM SANPHAM
				  WHERE NUOCSX = 'Trung Quoc'
				  ORDER BY GIA DESC)
