use QUANLYGIAOVU;

-------------------------Bai tap phan III------------------------------

-- 19. 
SELECT MAKHOA, TENKHOA
FROM KHOA
WHERE NGTLAP IN (SELECT TOP 1 NGTLAP
					FROM KHOA
					ORDER BY NGTLAP ASC)

-- 20. 
SELECT COUNT(*) AS 'GS or PGS'
FROM GIAOVIEN
WHERE HOCHAM IN ('GS','PGS')

-- 21.
SELECT MAKHOA, HOCVI, COUNT(*) 
FROM GIAOVIEN
WHERE HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS') GROUP BY MAKHOA, HOCVI;

-- 22. 
SELECT MAMH, KQUA, COUNT(*) FROM KETQUATHI GROUP BY MAMH, KQUA;

-- 23. 
SELECT MAGV, HOTEN 
FROM GIAOVIEN
WHERE MAGV IN (SELECT MAGVCN
				FROM LOP)
	AND MAGV IN (SELECT LOP.MAGVCN
				FROM  LOP
				WHERE LOP.MALOP IN (SELECT GIANGDAY.MALOP 
									FROM GIANGDAY 
									WHERE GIANGDAY.MALOP = LOP.MALOP
									GROUP BY MAGV, GIANGDAY.MALOP
									HAVING COUNT(MAGV) > 1))

-- 24. 
SELECT HO,TEN
FROM HOCVIEN 
WHERE MAHV IN (SELECT TRGLOP
				FROM LOP 
				WHERE SISO IN (SELECT MAX(SISO)
								FROM LOP))
-- 25. 
SELECT HO, TEN
FROM HOCVIEN
WHERE MAHV IN (SELECT TRGLOP
				FROM LOP
				WHERE TRGLOP IN (SELECT MAHV
								FROM KETQUATHI
								WHERE KQUA = 'Khong Dat'
								GROUP BY MAHV
								HAVING COUNT(DISTINCT MAMH) > 3))
