use QUANLYBANHANG;

-------------------------Bai tap phan III------------------------------

-- 31. 
SELECT MAKH, HOTEN, DOANHSO 
FROM KHACHHANG 
WHERE DOANHSO IN (SELECT TOP 3 DOANHSO
					FROM KHACHHANG 
					ORDER BY DOANHSO DESC)
ORDER BY DOANHSO DESC

-- 32. 
SELECT COUNT(MASP)
FROM SANPHAM
WHERE MASP IN (SELECT MASP
				FROM SANPHAM
				WHERE NUOCSX = 'Trung Quoc')

-- 33. 
SELECT NUOCSX, COUNT(DISTINCT MASP) AS TONGSOSANPHAM
FROM SANPHAM
GROUP BY NUOCSX

-- 34. 
SELECT NUOCSX, MAX(GIA) AS 'MAX', MIN(GIA) AS'MIN', AVG(GIA) AS GIATRUNGBINH
FROM SANPHAM
GROUP BY NUOCSX

-- 35. 
SELECT NGHD, SUM(TRIGIA) AS 'DOANH THU MOI NGAY'
FROM HOADON
GROUP BY NGHD

-- 36. 
SELECT MASP, SUM(SL) AS TONGSLSP
FROM CTHD 
WHERE SOHD IN (SELECT SOHD
				FROM HOADON
				WHERE MONTH(NGHD) = 10 
					AND YEAR(NGHD) = 2006)
GROUP BY MASP

-- 37. 
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU
FROM HOADON 
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)

-- 38. 
SELECT SOHD
FROM CTHD
GROUP BY SOHD
HAVING COUNT(MASP) > 3;

-- 39. 
SELECT SOHD
FROM CTHD
WHERE MASP IN (SELECT MASP
				FROM SANPHAM
				WHERE NUOCSX = 'Viet Nam')
GROUP BY SOHD
HAVING COUNT(MASP) = 3

-- 40. 
SELECT MAKH, HOTEN
FROM KHACHHANG
WHERE MAKH = (SELECT TOP 1 MAKH
				FROM HOADON
				GROUP BY MAKH
				ORDER BY COUNT(DISTINCT SOHD) DESC)

-- 41. 
SELECT TOP 1 MONTH(NGHD) AS 'THANG DOANH SO MAX'
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC

-- 42. 
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP = (SELECT TOP 1 MASP
				FROM CTHD
				WHERE SOHD IN (SELECT SOHD
								FROM HOADON
								WHERE YEAR(NGHD) = 2006)
				GROUP BY MASP
				ORDER BY SUM(SL) ASC)

-- 43. 
SELECT NUOCSX, MAX(GIA) AS MAX
FROM SANPHAM
GROUP BY NUOCSX
SELECT B.NUOCSX, MASP, TENSP
FROM (SELECT NUOCSX, MAX(GIA) AS MAX
		FROM SANPHAM
		GROUP BY NUOCSX) AS B LEFT JOIN SANPHAM S 
ON S.GIA = B.MAX 
WHERE B.NUOCSX = S.NUOCSX

-- 44. 
SELECT NUOCSX 
FROM SANPHAM 
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) > 2

-- 45. 
SELECT * 
FROM KHACHHANG
WHERE MAKH IN (SELECT TOP 1 MAKH 
				FROM HOADON
				WHERE MAKH IN (SELECT TOP 10 MAKH
								FROM HOADON 
								GROUP BY MAKH
								ORDER BY SUM(TRIGIA) DESC)
				GROUP BY MAKH
				ORDER BY COUNT(MAKH) DESC)