use QUANLYGIAOVU;

-------------------------Bai tap phan III------------------------------

-- 26. 
SELECT MAHV, HO, TEN
FROM HOCVIEN
WHERE MAHV IN (SELECT MAHV 
				FROM KETQUATHI
				WHERE DIEM >= 9 
					AND DIEM <= 10 
				GROUP BY MAHV
				HAVING COUNT(*) = (SELECT TOP 1 COUNT(*)
									FROM KETQUATHI
									WHERE DIEM >= 9 
										AND DIEM <= 10 
									GROUP BY MAHV
									ORDER BY COUNT(*) DESC))
-- 27. 
SELECT MALOP, MAHV, HO, TEN
FROM HOCVIEN 
WHERE (MALOP, MAHV) IN (SELECT MALOP, MAHV
						FROM KETQUATHI
						WHERE DIEM >= 9 
						GROUP BY MALOP, MAHV 
						ORDER BY COUNT(*) DESC)
						
-- 28. 
SELECT HOCKY, NAM, MAGV, COUNT(DISTINCT MAMH), COUNT(DISTINCT MALOP) 
FROM GIANGDAY GROUP BY HOCKY, NAM, MAGV;

-- 29. 
SELECT HOCKY, NAM, GIANGDAY.MAGV, HOTEN 
FROM GIAOVIEN, GIANGDAY 
WHERE GIANGDAY.MAGV IN (SELECT MAGV FROM GIANGDAY
			   GROUP BY HOCKY, NAM, MAGV 
			   ORDER BY COUNT(*) DESC LIMIT 1);

-- 30. 
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (SELECT MAMH
				FROM KETQUATHI
				WHERE LANTHI = 1
					AND KQUA = 'Khong Dat'
				GROUP BY MAMH
				HAVING COUNT(*) IN (SELECT TOP 1 COUNT(*)
									FROM KETQUATHI
									WHERE  LANTHI = 1
										AND KQUA = 'Khong Dat' 
									GROUP BY MAMH
									ORDER BY COUNT(*) DESC))
-- 31. 
SELECT MAHV, HO, TEN
FROM HOCVIEN
WHERE MAHV IN (SELECT MAHV 
				FROM KETQUATHI
				WHERE LANTHI = 1
					AND KQUA = 'Dat'
				GROUP BY MAHV
				HAVING COUNT(*) = (SELECT TOP 1 COUNT(*)
									FROM KETQUATHI
									WHERE LANTHI = 1
										AND KQUA = 'Dat'
									GROUP BY MAHV
									ORDER BY COUNT(*) DESC))
--32. 
SELECT MAHV, HO, TEN 
FROM HOCVIEN 
WHERE MAHV NOT IN (
    SELECT MAHV 
    FROM KETQUATHI 
    WHERE KQUA = 'Khong dat' AND LANTHI = (
        SELECT MAX(LANTHI) 
        FROM KETQUATHI
    )
);

--33.
SELECT MAHV, HO, TEN 
FROM HOCVIEN 
WHERE MAHV NOT IN (
    SELECT MAHV 
    FROM KETQUATHI 
    WHERE KQUA = 'Khong dat' AND LANTHI = 1
) AND MAHV IN (
    SELECT MAHV 
    FROM KETQUATHI 
    WHERE LANTHI = 1 
    GROUP BY MAHV 
    HAVING COUNT(DISTINCT MAMH) = (
        SELECT COUNT(*) 
        FROM MONHOC
    )
);

--34
SELECT MAHV, HO, TEN 
FROM HOCVIEN 
WHERE MAHV NOT IN (
    SELECT MAHV 
    FROM KETQUATHI 
    WHERE KQUA = 'Khong dat' AND LANTHI = (
        SELECT MAX(LANTHI) 
        FROM KETQUATHI
    )
) AND MAHV IN (
    SELECT MAHV 
    FROM KETQUATHI 
    WHERE LANTHI = (
        SELECT MAX(LANTHI) 
        FROM KETQUATHI
    ) 
    GROUP BY MAHV 
    HAVING COUNT(DISTINCT MAMH) = (
        SELECT COUNT(*) 
        FROM MONHOC
    )
);

--35
SELECT MAMH, MAHV, HO, TEN 
FROM HOCVIEN 
WHERE (MAMH, MAHV) IN (
    SELECT MAMH, MAHV 
    FROM KETQUATHI 
    WHERE DIEM = (
        SELECT MAX(DIEM) 
        FROM KETQUATHI 
        WHERE LANTHI = (
            SELECT MAX(LANTHI) 
            FROM KETQUATHI
        )
    ) 
    GROUP BY MAMH
);
