USE QUANLYBANHANG;

-------------------------Bai tap phan II------------------------------

--2
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN ('cay', 'quyen');

--3
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01';

--4
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000;

--5
SELECT MASP, TENSP
FROM SANPHAM
WHERE (NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA BETWEEN 30000 AND 40000;
