USE QUANLYGIAOVU;

-------------------------Bai tap phan I------------------------------

--CAU 11
SELECT MAHV, HO, TEN
FROM HOCVIEN
WHERE DATEDIFF(YEAR, NGSINH, GETDATE()) >= 18;

--CAU 12
SELECT MAMH, TUNGAY, DENNGAY
FROM GIANGDAY
WHERE TUNGAY < DENNGAY;

--CAU 13
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE DATEDIFF(YEAR, NGVL, GETDATE()) >= 22;

--CAU 14
SELECT MAMH, TENMH, TCLT, TCTH
FROM MONHOC
WHERE ABS(TCLT - TCTH) <= 5;
