USE QUANLYGIAOVU;

-------------------------Bai tap phan III------------------------------

-- 1.
SELECT LOP.TRGLOP, HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, HOCVIEN.NGSINH, LOP.MALOP
FROM HOCVIEN
JOIN LOP ON HOCVIEN.MAHV = LOP.TRGLOP;

-- 2. 
SELECT KETQUATHI.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.LANTHI, KETQUATHI.DIEM
FROM KETQUATHI
JOIN HOCVIEN ON KETQUATHI.MAHV = HOCVIEN.MAHV
JOIN LOP ON HOCVIEN.MALOP = LOP.MALOP
WHERE LOP.MALOP = 'K12' AND KETQUATHI.MAMH = 'CTRR'
ORDER BY HOCVIEN.HO, HOCVIEN.TEN;

-- 3.
SELECT KETQUATHI.MAHV, HOCVIEN.HO, HOCVIEN.TEN
FROM KETQUATHI
JOIN HOCVIEN ON KETQUATHI.MAHV = HOCVIEN.MAHV
WHERE KETQUATHI.LANTHI = 1 AND KETQUATHI.DIEM >= 5;

-- 4.
SELECT KETQUATHI.MAHV, HOCVIEN.HO, HOCVIEN.TEN
FROM KETQUATHI
JOIN HOCVIEN ON KETQUATHI.MAHV = HOCVIEN.MAHV
JOIN LOP ON HOCVIEN.MALOP = LOP.MALOP
WHERE LOP.MALOP = 'K11' AND KETQUATHI.MAMH = 'CTRR' AND KETQUATHI.LANTHI = 1 AND KETQUATHI.DIEM < 5;

-- 5.
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN
FROM HOCVIEN
WHERE HOCVIEN.MALOP = 'K12'
AND HOCVIEN.MAHV NOT IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE MAMH = 'CTRR' AND DIEM >= 5
);

